import { pgTable, text, timestamp, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// Admin-curated "Suggestions Library" — third-party video links (never
// uploaded bytes) an admin picks, or an AI discovery agent finds, tagged by
// category and shown to users as "check this out, whisper it to someone who
// might need it." Deliberately separate from uploaded_videos: there's no
// bytes/retention lifecycle here, just a curated pointer to someone else's
// video, same videoUrl/videoTitle/videoThumbnail/videoEmbedUrl/videoPlatform
// shape whisps already use for pasted URLs.
export const suggestedVideosTable = pgTable("suggested_videos", {
  id: text("id").primaryKey(),
  videoUrl: text("video_url").notNull(),
  videoTitle: text("video_title"),
  videoThumbnail: text("video_thumbnail"),
  videoEmbedUrl: text("video_embed_url"),
  videoPlatform: text("video_platform"), // 'youtube' | 'tiktok' | 'instagram' | 'facebook' | 'vimeo' | 'twitter'
  authorName: text("author_name"),
  // A video can belong to more than one category — a Postgres array,
  // same pattern as match_subscribers.categories, since this is
  // admin-curated tagging rather than the AI-ranked rank/score pairs
  // whisp_categories uses for auto-categorized whisps.
  categories: text("categories").array().notNull(),
  // Short "why this is worth sending" description, generated by Claude from
  // the scraped title (see lib/suggestionSummary.ts). null means not
  // attempted yet, 'pending' is the atomic claim a generation run takes
  // before it settles to 'ready' or 'unavailable' (same pattern as whisps'
  // aiTakeawayStatus).
  aiSummary: text("ai_summary"),
  aiSummaryStatus: text("ai_summary_status"), // null | 'pending' | 'ready' | 'unavailable'
  featured: boolean("featured").notNull().default(false),
  // 'pending' — inserted by the AI discovery agent, awaiting admin
  // approval before it's visible to users (see lib/suggestionAgent.ts).
  // 'published' — visible in the user-facing library (admin-added videos
  // start here directly; agent-found videos move here once approved).
  // 'archived' — soft-removed; never hard-deleted so a reference is never
  // a broken lookup, same posture as uploaded_videos' status lifecycle.
  status: text("status").notNull().default("published"),
  // Who/what added this row — lets the admin UI distinguish "I picked
  // this myself" from "the agent found this, still needs a look."
  source: text("source").notNull().default("admin"), // 'admin' | 'ai_agent'
  addedByUserId: text("added_by_user_id"), // internal users.id; null when source is 'ai_agent'
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  publishedAt: timestamp("published_at", { withTimezone: true }),
});

export const insertSuggestedVideoSchema = createInsertSchema(suggestedVideosTable).omit({ createdAt: true });
export type InsertSuggestedVideo = z.infer<typeof insertSuggestedVideoSchema>;
export type SuggestedVideo = typeof suggestedVideosTable.$inferSelect;
